import { nanoid } from "nanoid";

export const weeklyItems = {
	produce: [
		{ id: nanoid(), name: "Avocados", quantity: 4, purchased: false },
		{ id: nanoid(), name: "Apples", quantity: 4, purchased: false },
		{ id: nanoid(), name: "Bananas", quantity: 5, purchased: false },
	],
	bakery: [
		{ id: nanoid(), name: "Sandwich Bread", quantity: 1, purchased: false },
	],
	dryGoods: [
		{ id: nanoid(), name: "Chicken Broth", quantity: 1, purchased: false },
	],
	protein: [],
	dairy: [{ id: nanoid, name: "Greek Yogurt", quantity: 6, purchased: false }],
	frozen: [],
	other: [],
	drinks: [],
};

export const produce = [
	"Apples",
	"Avocados",
	"Bananas",
	"Green Onions",
	"White Onions",
	"Yellow Onions",
	"Red Onions",
	"Carrots",
	"Parsely",
	"Pears (Anjou)",
	"Pears (Asian)",
	"Jalapenos",
	"Chilis",
	"Bell Peppers",
	"Mangos",
	"Cabbage",
	"Salad Mix",
	"Kale (Bunch)",
	"Kale (Package)",
	"Spinach",
	"Lettuce",
	"Lemons",
	"Limes",
	"White Potatoes",
	"Red Potatoes",
	"Yellow Potatoes",
	"Cilantro",
	"Leeks",
	"Cherry/Grape Tomatoes",
	"Basil",
	"Rosemary",
	"Garlic (Bunch)",
	"Garlic (Bulb)",
	"Ginger",
	"Green Beans",
	"Snow Peas",
	"Sweet Potatoes (Bag)",
].sort();

export const bakery = [
	"Bagels",
	"Sandwich Bread",
	"Artisanal Bread",
	"Tortillas (Large)",
	"Tortillas (Small)",
	"Sourdough Bread",
	"Naan",
	"Hoagie Rolls",
	"Hamburger Buns",
	"Sausage Rolls",
].sort();

export const dryGoods = [
	"Black Beans",
	"White Rice",
	"Chocolate Bar",
	"Pretzels",
	"Basmati Rice",
	"Kidney Beans",
	"Pinto Beans",
	"Brown Rice",
	"Cannellini Beans",
	"Everything Bagel Seasoning",
	"Salt",
	"Flour",
	"Taco Seasoning",
	"Salsa",
	"Salsa Verde",
	"Tortilla Chips",
	"Hot Sauce",
	"Granola Bars",
	"Chocolate",
	"Chocolate Chips",
	"Pistachioes",
	"Almonds",
	"Dried Cranberries",
	"Almond Butter",
	"Tomato Paste",
	"Soy Sauce",
	"Sesame Oil",
	"Sesame Seeds",
	"Enchilada Sauce",
	"Pasta",
	"Chicken Broth",
	"Hot Cocoa Mix",
	"Snacks",
	"Canned San Marzanos",
	"Honey",
	"Curry Sauce",
	"Italian Bread Crumbs",
	"Panko",
].sort();

export const protein = [
	"Ground Chicken",
	"Ground Turkey",
	"Chicken Breast",
	"Chicken Thighs",
	"Shaved Beef",
	"Chicken Sausage (Italian)",
	"Chicken Sausage (Spicy)",
	"Turkey Bacon",
	"Ground Pork",
	"Ground Beef",
	"Pork Cutlets",
].sort();

export const dairy = [
	"Almond Milk",
	"Eggs (Dozen)",
	"Eggs (Half Dozen)",
	"Milk (1/2 Gal)",
	"Greek Yogurt",
	"Coffee Creamer",
	"Parmigiano Reggiano",
	"Sharp Cheddar (Block)",
	"Sharp Cheddar (Shredded)",
	"Mexican Cheese Blend",
	"Colby Jack (Block)",
	"Mozzarella (Whole)",
	"Mozzarella (Shredded)",
	"Oat Milk",
	"Cream Cheese",
	"Parmesan Cheese (Block)",
	"Goat Cheese",
].sort();

export const frozen = [
	"Pizza",
	"Corn",
	"Broccoli",
	"Green Beans",
	"Carrots",
	"Smoothie Fruit",
	"Ice Cream",
	"Gyoza Wrappers",
].sort();

export const other = [
	"Hand Soap",
	"Dish Soap",
	"Dish Sponge",
	"Clorox Wipes",
	"Swiffer Refills",
	"Pledge",
	"Toothpaste",
	"Tooth Brush",
	"Floss",
	"Freezer Bags",
	"Sandwich Bags",
	"Aluminum Foil",
	"Parchment Paper",
	"Saran Wrap",
	"Wax Paper",
].sort();

export const drinks = [
	"Kombucha",
	"Coconut Water",
	"Soda Water",
	"Cranberry Juice",
	"Orange Juice",
	"Tonic Water",
	"Distilled Water",
	"White Wine",
	"Red Wine",
	"Craft / Seasonal Beer (6)",
	"Fridge Beer (6) - Heineken",
	"Fridge Beer (12) - Heineken",
	"Fridge Beer (6) - Guinness",
	"Fridge Beer (12) - Guinness",
].sort();

// Meals
export const mealIdeas = [
	"Baked Tacos",
	"Lemon Chicken Scallopini",
	"Bulgogi",
	"Okinawan Taco Rice",
	"Gyudon",
	"Baked Chicken Katsu",
	"Vodka Sauce Pasta Bake",
	"Steak Street Tacos",
	"Lettuce Wraps",
	"Chicken Pot Pie",
	"Ginger Chicken Udon",
	"Black Bean Burgers",
	"Chicken Ramen",
	"Cacio e Pepe",
	"Gyoza",
	"Turkey Meatballs",
	"Turkey Black Bean Bake",
	"Baked Ziti",
	"Stuffed Peppers",
	"Broccoli Cheddar Soup",
	"Cannellini Beans & Tomatoes",
	"Carmelized Onion & Spinach Pasta",
	"Fried Rice",
	"Green Sauce Pasta",
	"Greek Meatballs w/ Lemon Orzo",
	"Enchiladas",
	"Soba",
	"Skillet Lemon Chicken & Orzo",
	"Honey Garlic Chicken",
	"Red Beans & Rice",
	"Risotto",
	"(Chicken) Cheesesteaks",
	"Asian Meatball Soup",
	"Pinto Beans & Rice",
	"Enchilada Rice",
	"Tortellini & Sausage Soup",
	"Mushroom & Garlic Spaghetti",
].sort();

export const mealList = [
	{ name: "Baked Tacos", url: "" },
	{
		name: "Lemon Chicken Scallopini",
		url: "https://www.saltandlavender.com/wprm_print/lemon-butter-chicken-scallopini",
	},
	{ name: "Bulgogi", url: "https://damndelicious.net/wprm_print/34905/" },
	{ name: "Okinawan Taco Rice", url: "" },
	{
		name: "Gyudon",
		url: "https://www.justonecookbook.com/wprm_print/gyudon-japanese-beef-rice-bowl",
	},
	{
		name: "Baked Chicken Katsu",
		url: "https://www.justonecookbook.com/wprm_print/58716",
	},
	{ name: "Vodka Sauce Pasta Bake", url: "" },
	{ name: "Steak Street Tacos", url: "" },
	{ name: "Chicken Pot Pie", url: "" },
	{
		name: "Ginger Chicken Udon",
		url: "https://www.bbcgoodfood.com/recipes/ginger-chicken-udon-noodles",
	},
	{
		name: "Black Bean Burgers",
		url: "https://www.loveandlemons.com/wprm_print/best-black-bean-burger",
	},
	{
		name: "Chicken Ramen",
		url: "https://www.forkknifeswoon.com/simple-homemade-chicken-ramen/print/17264/",
	},
	{
		name: "Cacio e Pepe",
		url: "https://www.gimmesomeoven.com/cacio-e-pepe/print-recipe/60551/",
	},
	{ name: "Gyoza", url: "https://www.justonecookbook.com/wprm_print/60570" },
	{ name: "Turkey Meatballs", url: "" },
	{ name: "Turkey Black Bean Bake", url: "" },
	{
		name: "Baked Ziti",
		url: "https://apaigeofpositivity.com/wprm_print/healthy-baked-ziti",
	},
	{
		name: "Stuffed Peppers",
		url: "https://belleofthekitchen.com/wprm_print/5854",
	},
	{ name: "Lettuce Wraps", url: "" },
	{
		name: "Broccoli Cheddar Soup",
		url: "https://www.instagram.com/reel/C_bmeJTymok/?igsh=dzlodGJpZ2Y3MWNk",
	},
	{
		name: "Cannellini Beans & Tomatoes",
		url: "https://www.instagram.com/p/C2FKlpAqUWj/",
	},
	{
		name: "Carmelized Onion & Spinach Pasta",
		url: "https://www.ambitiouskitchen.com/wprm_print/40632",
	},
	{
		name: "Fried Rice",
		url: "https://www.justonecookbook.com/wprm_print/75644",
	},
	{ name: "Green Sauce Pasta", url: "" },
	{
		name: "Greek Meatballs w/ Lemon Orzo",
		url: "https://braesbites.com/wprm_print/easy-greek-chicken-meatballs-with-lemon-orzo",
	},
	{ name: "Enchiladas", url: "" },
	{ name: "Soba", url: "" },
	{ name: "Skillet Lemon Chicken & Orzo", url: "" },
	{
		name: "Honey Garlic Chicken",
		url: "https://www.halfbakedharvest.com/honey-garlic-chicken/",
	},
	{ name: "Red Beans & Rice", url: "" },
	{ name: "Risotto", url: "" },
	{ name: "(Chicken) Cheesesteaks", url: "" },
	{ name: "Asian Meatball Soup", url: "" },
	{ name: "Pinto Beans & Rice", url: "" },
	{
		name: "Enchilada Rice",
		url: "https://damndelicious.net/2014/09/17/cheesy-enchilada-rice-skillet/",
	},
	{ name: "Tortellini & Sausage Soup", url: "" },
	{ name: "Mushroom & Garlic Spaghetti", url: "" },
	{
		name: "Chicken Ramen",
		url: "https://www.forkknifeswoon.com/simple-homemade-chicken-ramen/print/17264/",
	},
	{
		name: "Butter Chicken Curry",
		url: "https://therecipecritic.com/wprm_print/easy-butter-chicken",
	},
].sort();
